CREATE TYPE "display_status" AS ENUM (
	'	'active'',
	''deceased''
);

CREATE TABLE IF NOT EXISTS "Owner" (
	"owner_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ชื่อเจ้าของ
	"owner_name" VARCHAR(100) NOT NULL,
	"address" VARCHAR(255) NOT NULL,
	PRIMARY KEY("owner_id")
);

COMMENT ON COLUMN "Owner"."owner_name" IS 'ชื่อเจ้าของ';

CREATE TABLE IF NOT EXISTS "owner_phone" (
	"owner_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"phone" VARCHAR(20),
	PRIMARY KEY("owner_id")
);

CREATE INDEX "owner_phone_index_0"
ON "owner_phone" ("owner_id", "phone");

CREATE TABLE IF NOT EXISTS "pet" (
	"pet_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"owner_id" INTEGER NOT NULL,
	"pet_name" VARCHAR(20) NOT NULL,
	-- หมา แมว อื่นๆ
	"species" VARCHAR(20),
	-- พันธุ์
	"breed" VARCHAR(20),
	-- date of birth
	"dob" DATE,
	"display_status" DISPLAY_STATUS,
	PRIMARY KEY("pet_id")
);

COMMENT ON COLUMN "pet"."species" IS 'หมา แมว อื่นๆ';
COMMENT ON COLUMN "pet"."breed" IS 'พันธุ์';
COMMENT ON COLUMN "pet"."dob" IS 'date of birth';

CREATE TABLE IF NOT EXISTS "vet" (
	"vet_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"vet_name" VARCHAR(200) NOT NULL,
	PRIMARY KEY("vet_id")
);

CREATE TABLE IF NOT EXISTS "vet_specialization" (
	"vet_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ความเชี่ยวชาญ มีได้หลายด้าน
	"specailization" VARCHAR(255) NOT NULL,
	PRIMARY KEY("vet_id")
);

COMMENT ON COLUMN "vet_specialization"."specailization" IS 'ความเชี่ยวชาญ มีได้หลายด้าน';

CREATE INDEX "vet_specialization_index_0"
ON "vet_specialization" ("vet_id", "specailization");

CREATE TABLE IF NOT EXISTS "visit" (
	"pet_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"visit_no" INTEGER,
	"vet_id" INTEGER NOT NULL,
	"visit_date" TIMESTAMP NOT NULL,
	-- ตรวจระบุโรค
	"diagnosis" TEXT,
	"total_amount" DECIMAL,
	"receipt_print" BOOLEAN
);

COMMENT ON TABLE "visit" IS 'weak_entity';
COMMENT ON COLUMN "visit"."diagnosis" IS 'ตรวจระบุโรค';

CREATE INDEX "visit_index_0"
ON "visit" ("pet_id", "visit_no");

CREATE TABLE IF NOT EXISTS "medicine" (
	"med_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"med_name" VARCHAR(255),
	-- ราคายา อาจเปลี่ยนได้
	"unit_price" DECIMAL,
	-- หน่วยนับ เม็ด, ml อื่นๆ
	"unit" VARCHAR(255),
	PRIMARY KEY("med_id")
);

COMMENT ON COLUMN "medicine"."unit_price" IS 'ราคายา อาจเปลี่ยนได้';
COMMENT ON COLUMN "medicine"."unit" IS 'หน่วยนับ เม็ด, ml อื่นๆ';

CREATE TABLE IF NOT EXISTS "visit_medicine" (
	"pet_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"visit_no" INTEGER,
	"med_id" INTEGER,
	-- จำนวนที่สั่ง
	"quantity" INTEGER,
	-- จำนวนวันไม่ใช่วันที่
	"days" INTEGER,
	-- ราคา ณ วันตรวจ ห้ามเปลี่ยน
	"price_at_visit" DECIMAL,
	PRIMARY KEY("pet_id")
);

COMMENT ON COLUMN "visit_medicine"."quantity" IS 'จำนวนที่สั่ง';
COMMENT ON COLUMN "visit_medicine"."days" IS 'จำนวนวันไม่ใช่วันที่';
COMMENT ON COLUMN "visit_medicine"."price_at_visit" IS 'ราคา ณ วันตรวจ ห้ามเปลี่ยน';

CREATE INDEX "visit_medicine_index_0"
ON "visit_medicine" ("pet_id", "visit_no", "med_id");

ALTER TABLE "owner_phone"
ADD FOREIGN KEY("owner_id") REFERENCES "Owner"("owner_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pet"
ADD FOREIGN KEY("owner_id") REFERENCES "Owner"("owner_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pet"
ADD FOREIGN KEY("pet_id") REFERENCES "visit"("pet_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "vet"
ADD FOREIGN KEY("vet_id") REFERENCES "vet_specialization"("vet_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "visit"
ADD FOREIGN KEY("vet_id") REFERENCES "vet"("vet_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "visit_medicine"
ADD FOREIGN KEY("med_id") REFERENCES "medicine"("med_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "visit_medicine"
ADD FOREIGN KEY("pet_id", "visit_no") REFERENCES "visit"("pet_id", "visit_no")
ON UPDATE NO ACTION ON DELETE NO ACTION;