DROP TABLE IF EXISTS "owner" CASCADE;
DROP TABLE IF EXISTS "owner_phone" CASCADE;
DROP TABLE IF EXISTS "animal" CASCADE;
DROP TABLE IF EXISTS "vet" CASCADE;
DROP TABLE IF EXISTS "vet_specialty" CASCADE;
DROP TABLE IF EXISTS "visit" CASCADE;
DROP TABLE IF EXISTS "medicine" CASCADE;
DROP TABLE IF EXISTS "visit_medicine" CASCADE;
DROP TABLE IF EXISTS "receipt" CASCADE;

--เจ้าของสัตว์
CREATE TABLE "owner" (
	"owner_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"firsrt_name" VARCHAR(100) NOT NULL,
	"last_name" VARCHAR(100) NOT NULL,
	"address" VARCHAR(255) NOT NULL,
	PRIMARY KEY("owner_id")
);

COMMENT ON COLUMN "owner"."first_name"."last_name" IS 'ชื่อเจ้าของสัตว์';

--เบอร์โทร
CREATE TABLE "owner_phone" (
	"owner_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"phone_no" VARCHAR(20),
	"is_primary" VARCHAR(20) NOT NULL,
	PRIMARY KEY("is_primary")--เบอร์หลักได้เบอร์เดียว
);

CREATE INDEX "owner_phone_index_0"
ON "owner_phone" ("owner_id", "phone_no","is_primary");

--สัตว์เลี้ยง
CREATE TABLE "animal" (
	"animal_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"owner_id" INTEGER NOT NULL,
	"name" VARCHAR(20) NOT NULL,
	"species" VARCHAR(20),
	"sex" VARCHAR(20),
	"color" VARCHAR(20),
	"birth_date" DATE,
	PRIMARY KEY("animal_id")
);

--สัตวแพทย์
CREATE TABLE "vet" (
	"vet_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"license_no" INTEGER NOT NULL UNIQUE,
	"name" VARCHAR(100) NOT NULL,
	"start_date" DATE,
	PRIMARY KEY("vet_id")
);

--ความเชี่ยวชาญ
CREATE TABLE "vet_specialty" (
	"vet_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- ความเชี่ยวชาญ มีได้หลายด้าน
	"specialty" VARCHAR(255) NOT NULL,
	PRIMARY KEY("vet_id")
);

CREATE INDEX "vet_specialty_index_0"
ON "vet_specialty" ("vet_id", "specialty");

--การเข้ารับบริการ
CREATE TABLE "visit" (
	"animal_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"visit_no" INTEGER NOT NULL,
	"visit_date" TIMESTAMP NOT NULL,
	"weight" DECIMAL,
	"temperature" DECIMAL,
	--อาการ
	"symptom" TEXT,
	-- ตรวจระบุโรค
	"diagnosis" TEXT,
	"vet_id" INTEGER ,
	PRIMARY KEY("animal_id","visit_no")
); 

CREATE INDEX "visit_index_0"
ON "visit" ("animal_id", "visit_no");

--ยา
CREATE TABLE "medicine" (
	"medicine_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255),
	"unit" VARCHAR(255),
	-- ราคายา อาจเปลี่ยนได้
	"unit_price" DECIMAL,
	PRIMARY KEY("medicine_id")
);

--การจ่ายยา
CREATE TABLE "visit_medicine" (
	"animal_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"visit_no" INTEGER NOT NULL,
	"medicine_id" INTEGER NOT NULL,
	-- จำนวนที่สั่ง
	"dosage" INTEGER,
	-- จำนวนวันไม่ใช่วันที่
	"days" INTEGER,
	PRIMARY KEY("animal_id")
);

CREATE INDEX "visit_medicine_index_0"
ON "visit_medicine" ("animal_id", "visit_no", "medicine_id");

--ใบเสร็จ
CREATE TABLE "receipt" (
	"receipt_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"animal_id" INTEGER NOT NULL,
	"visit_no" INTEGER NOT NULL,
	--จ่ายเมื่อ
	"paid_at" TIMESTAMP NOT NULL,
	"total_amount" DECIMAL NOT NULL,
	PRIMARY KEY("receipt_id")
);

--เหลือเขียนความสัมพันธ์์
--ยังไม่ได้แก้ไข
ALTER TABLE "owner_phone"
ADD FOREIGN KEY("owner_id") REFERENCES "owner"("owner_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "animal"
ADD FOREIGN KEY("owner_id") REFERENCES "owner"("owner_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pet"
ADD FOREIGN KEY("pet_id") REFERENCES "visit"("pet_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "vet"
ADD FOREIGN KEY("vet_id") REFERENCES "vet_specialization"("vet_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "visit"
ADD FOREIGN KEY("vet_id") REFERENCES "vet"("vet_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "visit_medicine"
ADD FOREIGN KEY("med_id") REFERENCES "medicine"("med_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "visit_medicine"
ADD FOREIGN KEY("pet_id", "visit_no") REFERENCES "visit"("pet_id", "visit_no")
ON UPDATE NO ACTION ON DELETE NO ACTION;